### ISSUE TITLE
Don't use bold as default font for HTML fields

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/rol#3]
The CSS currently sets the font to bold for the various HTML fields, this means that HTML markup for bold doesn't make any difference to the display of the text.

Simply removing the "bold" font weighting from the CSS file should reflect this change.

It might be worth fading the colour in the background images so that the contrast is still good between the non-bold font and the sheet backgroundl.

**Comment by Genii-Locorum** [comment]
I've added this to the project plan - will aim to sort it whilst I do ugrades to Foundry V12 (might take a week or two)

**Comment by Genii-Locorum** [comment]
This was the first venture in to writing a Foundry System (I know, it shows) - so much I would probably go back and do differently.  Thank you for calling these out.  

I've put the changes in for just the "investigator" section, removed the input background color and lightened the background image.  Now blame my failing eyesight but I'm worriedthe contract isn't there -so I'm tempted to put the bold back in for the input (by changing the CSS rather than the inidividual HTML fields) but would welcome your thoughts.

![tom](https://github.com/Genii-Locorum/rol/assets/121451824/0afa1d33-710b-4eab-8efe-3edb95316a39)

Cheers

**Comment by Genii-Locorum** [comment]
Adjustments made in Release 13.  Thank you again for your help and insight @farling42
